### ISSUE TITLE
Transaction cost

### ISSUE THREAD

**Issue by svenpopping** [WISVCH/payments#2]
The transaction cost should be € 0,35 because the € 0,29 is excl VAT.

**Comment by praseodym** [comment]
Pinnen is ook niet gratis, maar toch hoef je daar bij CH niks extra's voor te betalen?

**Comment by skamoen** [comment]
Checked with Karim. Pin transactions aren't charged per transaction, so that's not directly comparable. Until decided otherwise by the board, the default setting will be charging it separately for each order.

**Comment by martijnjanssen** [comment]
That still is no answer for this issue. This issue is about changing the amount charged for a transaction, not whether we should charge anything.
