### ISSUE TITLE
Return JSON response on error

### ISSUE THREAD

**Issue by TimvdLippe** [WISVCH/payments#38]
When an error occurse (400+ or 500+), a Whitelabel Error Page is shown. It indicates that `This application has no explicit mapping for /error, so you are seeing this as a fallback.`.

It is nicer for consumers of the API to receive a JSON response with the exception name, status code and exception message.

**Comment by skamoen** [comment]
Are you sure you're getting this as well when sending json? I think Spring replies based on the content type.

**Comment by TimvdLippe** [comment]
Oh good point, I was using the browser to receive the error. I can confirm that
```js
async function f() {
  const request = await fetch('https://ch.tudelft.nl/payments/api/products/SYMPOSIUM/1234');
  console.log(await request.json())
}
f();
```
indeed returns the format I was looking for!
